import 'package:flutter/material.dart';
import 'package:digit_to_word/digit_to_word.dart';
import 'dart:math';

class HomePage extends StatefulWidget {
  const HomePage({super.key, required this.title});
  final String title;

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  TextEditingController _controller = new TextEditingController();
  int digit = 0;
  String digitText = "";

  @override
  void initState() {
    super.initState();
    int val = Random().nextInt(2000);
    changeText('$val');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Hi Tobi'),
        foregroundColor: const Color.fromARGB(255, 255, 255, 255),
        backgroundColor: const Color.fromARGB(255, 200, 4, 4),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('Random N° generated by Pucky: $digit'),
            TextField(
              controller: _controller,
              decoration: InputDecoration(labelText: 'Enter a number'),
              onChanged: (text) => {changeText(text)},
              autofocus: false,
            ),
            Text(digitText)
          ],
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }

  void changeText(String text) async {
    setState(() {
      digit = int.parse(text == "" ? "0" : text);
    });

    setState(() {
      digitText = DigitToWord.translate(
        digit,
        withDashes: true,
      );
    });

    //await Future.delayed(const Duration(seconds: 1));

    setState(() {
      _controller = new TextEditingController(text: '$digit');
    });
  }
}
